name: Ubuntu GCC Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build_ubuntu_gcc:
    name: Ubuntu GCC
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu GCC",
            os: ubuntu-latest,
            artifact: "ubuntu_gcc.7z",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            archiver: "7z a",
            generators: "Ninja"
          }

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build cmake
          ninja --version
          cmake --version
          gcc --version

      - name: Init Submodule
        run: |
          git submodule init
          git submodule update

      - name: Configure
        shell: bash
        run: |
          cd 02
          cmake \
            -S . \
            -B . \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -G "${{ matrix.config.generators }}"

      - name: Build
        shell: bash
        run: |
          cd 02
          cmake --build . --config ${{ matrix.config.build_type }}

      - name: Install Strip
        shell: bash
        run: |
          cd 02
          cmake --install . --strip

      - name: Pack
        shell: bash
        working-directory: 02/bin
        run: |
          ls -laR
          ${{ matrix.config.archiver }} ../${{ matrix.config.artifact }} .

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ./02/${{ matrix.config.artifact }}
          name: ${{ matrix.config.artifact }}
