name: Windows MinGW Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    name: Windows MinGW
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          choco install ninja cmake mingw
          ninja --version
          cmake --version
      - name: Configure
        shell: bash
        run: |
          cd 01
          mkdir build
          mkdir instdir
          cmake \
            -S . \
            -B . \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir
      - name: Build
        shell: bash
        run: |
          cd 01
          cmake --build . --config Release
      - name: Install Strip
        shell: bash
        run: |
          cd 01
          cmake --install . --strip
      - name: Pack
        shell: bash
        working-directory: 01/instdir
        run: |
          ls -laR
          7z a ../windows_mingw.7z .
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ./01/windows_mingw.7z
          name: windows_mingw.7z
